one explicit hypothesis solution for level 8
adyavanapalli/natural-number-game pull request #3
Opened 2021-12-10 03:48 UTC by robinsonkwame

Uses rewrite directly to prove b=0 and resolves the remaining subgoal simply (`apply h`)

2021-12-10 10:50 UTC, adyavanapalli requested changes
Thank you for your PR! I will approve these changes if you can remove the comments.

2021-12-10 17:36 UTC, robinsonkwame commented
Great, I removed the comments and changed h to h₁

2021-12-11 00:53 UTC, adyavanapalli requested changes

2021-12-11 00:53 UTC, adyavanapalli commented on advanced-addition-world/8
>  rw ← add_zero a at h₁,
Since only one hypothesis is used here, consider changing `h₁` to just `h`.

2021-12-12 20:53 UTC, robinsonkwame commented
how's that?

2021-12-12 23:45 UTC, adyavanapalli commented
Perfect. Thanks for your contribution!

2021-12-12 23:45 UTC, merged